// app/layout.js (or similar)
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "./components/Footer";
import PageTransition from "@/app/components/PageTransition"; // Import PageTransition

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <PageTransition>{children}</PageTransition> {/* Wrap children with PageTransition */}
        <Footer />
      </body>
    </html>
  );
}
